#!/bin/sh

gitleak_pre_commit_url="https://raw.githubusercontent.com/vsk44/git-leak-pre-commit-hook-script/main/git-leak-pre-commit.py"
pre_commit_url="https://raw.githubusercontent.com/vsk44/git-leak-pre-commit-hook-script/main/pre-commit"
pre_commit_content="python3 git-leak-pre-commit.py"

# Get the path to .git/hooks
hooks_dir=$(git rev-parse --git-dir)/hooks
pre_commit_hook="$hooks_dir/pre-commit"

# Download the script
curl -o "$hooks_dir/git-leak-pre-commit.py" "$gitleak_pre_commit_url"

# Check if pre-commit hook already exists
if [ -f "$pre_commit_hook" ]; then
    # Check if the required content is present in pre-commit hook
    if ! grep -q "$pre_commit_content" "$pre_commit_hook"; then
        # Append the required content to pre-commit hook
        echo "$pre_commit_content" >> "$pre_commit_hook"
        echo "Appended to existing pre-commit hook."
    else
        echo "Pre-commit hook is already configured."
    fi
else
    # Create a pre-commit hook script
    curl -o "$pre_commit_hook" "$pre_commit_url" > "$pre_commit_hook"
    echo "Created pre-commit hook."
fi

# Grant executive rights
chmod +x "$hooks_dir/git-leak-pre-commit.py"
chmod +x "$hooks_dir/pre-commit"

echo "Git Leaks pre-commit hook installed successfully!"